server:
  port: 8080

spring:
  datasource:
    name: test
    url: jdbc:mysql://10.242.220.176:3306/test
    username: root
    password: BaoBao1205B201
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.example.demo.entity  # 注意：对应实体类的路径
